apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bullfinch-api
  namespace: bullfinch
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: bullfinch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bullfinch-api
                port:
                  number: 80
