apiVersion: v1
kind: Secret
metadata:
  name: bullfinch-env
  namespace: bullfinch
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "http://host.docker.internal:5000"

  HEALTH_MODEL_URI: "models:/bullfinch-health-lgbm@prod"
  FORECAST_MODEL_H1_URI: "models:/bullfinch-health-h1@prod"
  FORECAST_MODEL_H7_URI: "models:/bullfinch-trunk-lgbm-h7@prod"
