apiVersion: v1
kind: Secret
metadata:
  name: bullfinch-env
  namespace: bullfinch
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: "file:///app/mlruns"
  HEALTH_MODEL_URI: "file:///app/mlruns/798548184845564305/models/m-298c1ba457a4416f82359de9fdbe33f5/artifacts"
  FORECAST_MODEL_H1_URI: "file:///app/mlruns/798548184845564305/models/m-c4743969f84c46a7a34270a27dbc68bd/artifacts"
  FORECAST_MODEL_H7_URI: "file:///app/mlruns/798548184845564305/models/m-d8b5c7a191504752adcc53eb9a7ce373/artifacts"
